server:
  port: 0 #포트를 동적으로 할당받기 위해 0으로 변경

spring:
  application:
    name: user-service

eureka:
  instance:
    # 인스턴스 id를 동적으로 할당받아 인스턴스 id와 port번호를 출력
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  clinet:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.